### ISSUE TITLE
Snap installation fails on a Vagrant VM

### ISSUE THREAD

**Issue by akcano** [canonical/workshop#31]
While trying out #29:
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.define "jammy"
```
Vagrant provider: ``virtualbox`` on Ubuntu 22.04.

```
vagrant@ubuntu2204:~$ ./snap_install.sh 
++ git clone https://github.com/canonical/workspace.git
Cloning into 'workspace'...
remote: Enumerating objects: 3584, done.
remote: Counting objects: 100% (431/431), done.
remote: Compressing objects: 100% (207/207), done.
remote: Total 3584 (delta 279), reused 258 (delta 220), pack-reused 3153
Receiving objects: 100% (3584/3584), 1.02 MiB | 5.46 MiB/s, done.
Resolving deltas: 100% (2179/2179), done.
++ cd workspace
++ git fetch origin pull/29/head:PR29
From https://github.com/canonical/workspace
 * [new ref]         refs/pull/29/head -> PR29
++ git checkout PR29
Switched to branch 'PR29'
++ sudo snap install snapcraft --classic
snap "snapcraft" is already installed, see 'snap help refresh'
++ snapcraft
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: multipass socket access denied
launch failed: multipass socket access denied
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

**Comment by dmitry-lyfar** [comment]
I think that, more specifically, the issue is about _building_ the snap with snapcraft, not _installing_ it. This is due to the nested virtualisation turned off by default and is related to how (and why) snapcraft launches a VM to build a clean snap.  An expected user journey would be doing that on their host machine and snapcraft taking care of the rest. Running snapcraft in a VM should be supplied with the provider's instructions on how to turn the nested virtualisation on (e.g. for multipass, vagrant an so on). 

We use snapcraft to build snap as part of the installation instructions because we want to keep snaps private. When closer to releasing publicly, we'll introduce a GitHub action to publish the snap for us and shrink the installation instruction to `snap install`. Given that, I suggest we close the issue. (Also, I considered the option of making snap unlisted in the store. Thus, only people who know the snap name would be able to install it. But, for the sake of not exposing it anyhow, decided to go with building it).

**Comment by akcano** [comment]
Agree; closing the issue.
Made a note to cover the VM scenario in the future (probably as a howto).
